# Generated by Django 4.2 on 2023-05-15 15:50

from django.db import migrations, models
import video.models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='video',
            field=models.FileField(default='', upload_to=video.models.upload_location),
        ),
    ]
