# Generated by Django 4.2 on 2023-05-15 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0003_post_datum_post_hely_post_tancos_post_tanctipus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='body',
        ),
    ]
